[2023-05-04 14:30:49,783][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 14:30:49,801][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 14:30:49,802][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 14:30:49,933][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 14:30:49,942][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 14:30:49,955][__main__][INFO] - Instantiating loggers...
[2023-05-04 14:30:49,956][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 14:31:02,897][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 14:31:03,008][__main__][INFO] - Logging hyperparameters!
[2023-05-04 14:31:03,028][__main__][INFO] - Starting inference!
[2023-05-04 14:31:23,948][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_14-30-49
[2023-05-04 14:31:23,949][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 14:36:41,896][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 14:36:41,912][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 14:36:41,913][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 14:36:42,040][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 14:36:42,057][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 14:36:42,070][__main__][INFO] - Instantiating loggers...
[2023-05-04 14:36:42,071][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 14:37:12,737][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 14:37:12,755][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 14:37:12,755][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 14:37:12,886][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 14:37:12,897][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 14:37:12,912][__main__][INFO] - Instantiating loggers...
[2023-05-04 14:37:12,913][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 14:37:19,028][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 14:37:19,137][__main__][INFO] - Logging hyperparameters!
[2023-05-04 14:37:19,156][__main__][INFO] - Starting inference!
[2023-05-04 14:37:39,030][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_14-37-12
[2023-05-04 14:37:39,031][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 15:29:38,284][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 15:29:38,302][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 15:29:38,302][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 15:29:38,432][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 15:29:38,441][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 15:29:38,454][__main__][INFO] - Instantiating loggers...
[2023-05-04 15:29:38,455][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 15:29:44,708][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 15:29:44,816][__main__][INFO] - Logging hyperparameters!
[2023-05-04 15:29:44,835][__main__][INFO] - Starting inference!
[2023-05-04 15:30:02,767][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_15-29-38
[2023-05-04 15:30:02,767][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 16:22:33,910][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 16:22:33,926][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 16:22:33,927][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 16:22:34,046][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 16:22:34,055][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 16:22:34,068][__main__][INFO] - Instantiating loggers...
[2023-05-04 16:22:34,069][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 16:22:41,262][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 16:22:41,367][__main__][INFO] - Logging hyperparameters!
[2023-05-04 16:22:41,384][__main__][INFO] - Starting inference!
[2023-05-04 16:38:29,793][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 16:38:29,809][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 16:38:29,810][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 16:38:29,945][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 16:38:29,957][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 16:38:29,984][__main__][INFO] - Instantiating loggers...
[2023-05-04 16:38:29,985][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 16:38:36,253][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 16:38:36,361][__main__][INFO] - Logging hyperparameters!
[2023-05-04 16:38:36,379][__main__][INFO] - Starting inference!
[2023-05-04 16:38:54,508][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 94, in infer
    x_deter = [model.decode(batch[1]) for batch in prediction]
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 94, in <listcomp>
    x_deter = [model.decode(batch[1]) for batch in prediction]
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module.py", line 72, in decode
    return self.decoder(z)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
[2023-05-04 16:38:54,511][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_16-38-29
[2023-05-04 16:38:54,512][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 16:42:47,607][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 16:42:47,623][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 16:42:47,623][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 16:42:47,748][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 16:42:47,756][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 16:42:47,767][__main__][INFO] - Instantiating loggers...
[2023-05-04 16:42:47,768][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 16:42:54,306][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 16:42:54,419][__main__][INFO] - Logging hyperparameters!
[2023-05-04 16:42:54,437][__main__][INFO] - Starting inference!
[2023-05-04 16:43:12,544][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 94, in infer
    x_deter = [model.decode(batch[1]) for batch in prediction]
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 94, in <listcomp>
    x_deter = [model.decode(batch[1]) for batch in prediction]
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module.py", line 72, in decode
    return self.decoder(z)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
[2023-05-04 16:43:12,548][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_16-42-47
[2023-05-04 16:43:12,548][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:00:35,303][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:00:35,319][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:00:35,319][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:00:35,440][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:00:35,448][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:00:35,460][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:00:35,461][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:00:41,715][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:00:41,826][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:00:41,844][__main__][INFO] - Starting inference!
[2023-05-04 17:01:16,998][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-00-35
[2023-05-04 17:01:16,998][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:24:08,231][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:24:08,247][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:24:08,248][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:24:08,367][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:24:08,375][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:24:08,386][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:24:08,387][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:24:14,748][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:24:14,850][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:24:14,868][__main__][INFO] - Starting inference!
[2023-05-04 17:24:33,061][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    torch.save(datamodule.data_test().model_output_to_pose(xhat),  directory + "/xhat_anim_train.pt")
TypeError: 'Subset' object is not callable
[2023-05-04 17:24:33,065][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-24-08
[2023-05-04 17:24:33,065][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:26:18,391][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:26:18,408][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:26:18,409][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:26:18,536][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:26:18,545][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:26:18,557][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:26:18,558][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:26:24,672][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:26:24,782][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:26:24,800][__main__][INFO] - Starting inference!
[2023-05-04 17:26:43,907][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    torch.save(datamodule.train_dataloader().model_output_to_pose(xhat),  directory + "/xhat_anim_train.pt")
AttributeError: 'DataLoader' object has no attribute 'model_output_to_pose'
[2023-05-04 17:26:43,910][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-26-18
[2023-05-04 17:26:43,910][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:27:30,110][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:27:30,126][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:27:30,127][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:27:30,248][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:27:30,256][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:27:30,268][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:27:30,269][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:27:36,448][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:27:36,561][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:27:36,578][__main__][INFO] - Starting inference!
[2023-05-04 17:27:55,669][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    torch.save(datamodule.train_dataloader().dataset.model_output_to_pose(xhat),  directory + "/xhat_anim_train.pt")
TypeError: model_output_to_pose() takes 1 positional argument but 2 were given
[2023-05-04 17:27:55,672][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-27-29
[2023-05-04 17:27:55,673][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:31:35,524][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:31:35,539][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:31:35,540][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:31:35,660][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:31:35,669][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:31:35,681][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:31:35,682][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:31:42,489][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:31:42,614][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:31:42,631][__main__][INFO] - Starting inference!
[2023-05-04 17:32:01,482][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    torch.save(datamodule.train_dataloader().dataset.model_output_to_pose(y = xhat),  directory + "/xhat_anim_train.pt")
TypeError: model_output_to_pose() got multiple values for argument 'y'
[2023-05-04 17:32:01,485][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-31-35
[2023-05-04 17:32:01,485][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:36:03,035][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:36:03,051][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:36:03,052][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:36:03,170][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:36:03,178][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:36:03,189][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:36:03,190][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:36:09,777][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:36:09,900][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:36:09,921][__main__][INFO] - Starting inference!
[2023-05-04 17:36:29,490][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    torch.save(datamodule.train_dataloader().dataset.model_output_to_pose(y = xhat),  directory + "/xhat_anim_train.pt")
TypeError: model_output_to_pose() got multiple values for argument 'y'
[2023-05-04 17:36:29,493][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-36-02
[2023-05-04 17:36:29,493][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 17:41:22,317][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:41:22,332][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:41:22,333][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:41:22,454][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:41:22,462][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:41:22,474][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:41:22,475][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:41:32,625][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:41:32,641][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:41:32,641][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:41:32,764][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:41:32,772][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:41:32,784][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:41:32,785][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:44:04,101][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 17:44:04,119][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 17:44:04,119][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 17:44:04,244][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 17:44:04,255][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 17:44:04,268][__main__][INFO] - Instantiating loggers...
[2023-05-04 17:44:04,268][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 17:44:10,692][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 17:44:10,801][__main__][INFO] - Logging hyperparameters!
[2023-05-04 17:44:10,818][__main__][INFO] - Starting inference!
[2023-05-04 17:45:31,947][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_17-44-03
[2023-05-04 17:45:33,796][src.utils.utils][INFO] - Closing wandb!
[2023-05-04 19:14:34,553][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-04 19:14:34,557][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-04 19:14:34,557][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-04 19:14:34,585][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-04 19:14:34,587][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-04 19:14:34,592][__main__][INFO] - Instantiating loggers...
[2023-05-04 19:14:34,593][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-04 19:14:39,523][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-04 19:14:39,568][__main__][INFO] - Logging hyperparameters!
[2023-05-04 19:14:39,573][__main__][INFO] - Starting inference!
[2023-05-04 19:14:49,837][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-04_19-14-34
[2023-05-04 19:14:49,837][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 10:39:37,737][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 10:39:37,742][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 10:39:37,742][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 10:39:37,782][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 10:39:37,786][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-05 10:39:37,798][__main__][INFO] - Instantiating loggers...
[2023-05-05 10:39:37,799][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 10:39:42,640][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 10:39:42,690][__main__][INFO] - Logging hyperparameters!
[2023-05-05 10:39:42,695][__main__][INFO] - Starting inference!
[2023-05-05 10:40:02,403][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_10-39-37
[2023-05-05 10:40:02,403][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 10:45:15,883][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 10:45:15,887][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 10:45:15,887][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 10:45:15,918][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 10:45:15,920][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-05 10:45:15,931][__main__][INFO] - Instantiating loggers...
[2023-05-05 10:45:15,932][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 10:45:21,147][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 10:45:21,200][__main__][INFO] - Logging hyperparameters!
[2023-05-05 10:45:21,205][__main__][INFO] - Starting inference!
[2023-05-05 10:45:39,937][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_10-45-15
[2023-05-05 10:45:39,938][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 10:56:47,578][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 10:56:47,594][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 10:56:47,595][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 10:56:47,718][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 10:56:47,726][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-05 10:56:47,738][__main__][INFO] - Instantiating loggers...
[2023-05-05 10:56:47,739][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 10:56:54,154][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 10:56:54,279][__main__][INFO] - Logging hyperparameters!
[2023-05-05 10:56:54,297][__main__][INFO] - Starting inference!
[2023-05-05 11:06:21,236][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:06:21,252][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:06:21,253][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:06:21,371][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:06:21,379][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-05 11:06:21,392][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:06:21,392][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:06:27,774][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:06:27,890][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:08:20,123][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:08:20,139][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:08:20,140][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:08:20,260][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:08:20,268][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-05 11:08:20,280][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:08:20,281][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:08:25,697][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:08:25,813][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:08:40,281][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 76, in infer
    vae = torch.load(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:08:42,562][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-06-21
[2023-05-05 11:08:51,197][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 11:22:19,491][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:22:19,506][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:22:19,507][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:22:19,611][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:22:19,619][__main__][INFO] - Instantiating model <src.models.beta_vae_module.old_vae>
[2023-05-05 11:22:53,690][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.models.beta_vae_module.old_vae'; 'src.models.beta_vae_module' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.beta_vae_module.old_vae':
ModuleNotFoundError("No module named 'src.models.beta_vae_module.old_vae'; 'src.models.beta_vae_module' is not a package")
Are you sure that 'old_vae' is importable from module 'src.models.beta_vae_module'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 55, in infer
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.beta_vae_module.old_vae', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[2023-05-05 11:22:53,702][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-22-19
[2023-05-05 11:23:19,652][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:23:19,668][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:23:19,669][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:23:19,775][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:23:19,783][__main__][INFO] - Instantiating model <src.models.beta_vae_module.old_vae>
[2023-05-05 11:24:08,809][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.models.beta_vae_module.old_vae'; 'src.models.beta_vae_module' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.beta_vae_module.old_vae':
ModuleNotFoundError("No module named 'src.models.beta_vae_module.old_vae'; 'src.models.beta_vae_module' is not a package")
Are you sure that 'old_vae' is importable from module 'src.models.beta_vae_module'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 55, in infer
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.beta_vae_module.old_vae', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[2023-05-05 11:24:09,842][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-23-19
[2023-05-05 11:25:21,279][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:25:21,295][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:25:21,296][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:25:21,407][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:25:21,415][__main__][INFO] - Instantiating model <src.models.old_vae>
[2023-05-05 11:25:43,367][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 55, in infer
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 144, in _resolve_target
    raise InstantiationException(msg)
hydra.errors.InstantiationException: Expected a callable target, got '<module 'src.models.old_vae' from '/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/old_vae.py'>' of type 'module'
full_key: model
[2023-05-05 11:25:44,651][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-25-21
[2023-05-05 11:27:37,431][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:27:37,447][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:27:37,448][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:27:37,555][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:27:37,563][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:28:14,584][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:28:16,875][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:28:26,235][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:28:30,659][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:28:47,032][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 76, in infer
    vae = torch.load(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:28:48,814][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-27-37
[2023-05-05 11:28:50,914][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 11:30:15,207][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:30:15,223][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:30:15,223][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:30:15,331][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:30:15,339][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:30:45,371][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:30:50,714][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:31:03,007][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:31:03,136][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:31:41,834][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 76, in infer
    vae = torch.load(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:32:52,397][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:32:52,413][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:32:52,414][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:32:52,521][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:32:52,529][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:32:52,534][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:32:52,534][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:32:57,736][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:32:57,851][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:33:33,399][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 76, in infer
    m = torch.load(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:33:33,406][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-32-52
[2023-05-05 11:33:33,407][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 11:33:44,301][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:33:44,318][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:33:44,319][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:33:44,429][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:33:44,437][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:33:44,442][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:33:44,442][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:33:50,280][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:33:50,394][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:35:17,970][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 76, in infer
    m = torch.load(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:35:20,952][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-33-44
[2023-05-05 11:35:26,379][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 11:37:48,128][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:37:48,145][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:37:48,146][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:37:48,253][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:37:48,262][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:37:48,267][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:37:48,267][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:37:53,736][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:37:53,856][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:37:59,068][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 164, in infer
    m = torch.load(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:38:00,817][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-37-47
[2023-05-05 11:38:02,257][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 11:40:19,804][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:40:19,820][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:40:19,820][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:40:19,936][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:40:19,944][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:40:19,950][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:40:19,950][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:40:25,093][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:40:25,208][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:40:29,695][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 164, in infer
    m = torch.load("logs/model")
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 11:40:30,634][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_11-40-19
[2023-05-05 11:40:32,179][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 11:42:48,318][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 11:42:48,336][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 11:42:48,337][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 11:42:48,446][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 11:42:48,454][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 11:42:48,459][__main__][INFO] - Instantiating loggers...
[2023-05-05 11:42:48,460][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 11:42:53,713][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 11:42:53,828][__main__][INFO] - Logging hyperparameters!
[2023-05-05 11:43:17,569][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 164, in infer
    m = torch.load("logs/model.pt")
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'VAE'
[2023-05-05 15:12:56,949][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 15:12:56,971][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 15:12:56,972][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 15:12:57,077][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 15:12:57,086][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 15:12:57,093][__main__][INFO] - Instantiating loggers...
[2023-05-05 15:12:57,094][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 15:13:03,777][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 15:13:03,901][__main__][INFO] - Logging hyperparameters!
[2023-05-05 15:15:37,573][__main__][INFO] - Starting inference!
[2023-05-05 15:15:50,416][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 83, in infer
    prediction = trainer.predict(model, dataloaders = datamodule.train_dataloader(shuffle=False))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 803, in predict
    model = _maybe_unwrap_optimized(model)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/utilities/compile.py", line 125, in _maybe_unwrap_optimized
    raise TypeError(
TypeError: `model` must be a `LightningModule` or `torch._dynamo.OptimizedModule`, got `VAE`
[2023-05-05 15:15:50,426][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_15-12-56
[2023-05-05 15:15:50,426][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 15:17:16,898][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 15:17:16,914][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 15:17:16,915][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 15:17:17,031][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 15:17:17,039][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 15:17:17,045][__main__][INFO] - Instantiating loggers...
[2023-05-05 15:17:17,046][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 15:17:23,581][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 15:17:23,704][__main__][INFO] - Logging hyperparameters!
[2023-05-05 15:17:29,701][__main__][INFO] - Starting inference!
[2023-05-05 15:19:14,685][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_15-17-16
[2023-05-05 15:19:14,685][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 16:44:22,670][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 16:44:22,674][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 16:44:22,674][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 16:44:22,703][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 16:44:22,705][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 16:44:22,710][__main__][INFO] - Instantiating loggers...
[2023-05-05 16:44:22,710][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 16:44:28,229][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 16:44:28,278][__main__][INFO] - Logging hyperparameters!
[2023-05-05 16:44:28,288][__main__][INFO] - Starting inference!
[2023-05-05 16:44:46,890][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_16-44-22
[2023-05-05 16:44:46,890][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 16:45:01,430][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 16:45:01,447][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 16:45:01,447][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 16:45:01,552][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 16:45:01,560][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 16:45:01,565][__main__][INFO] - Instantiating loggers...
[2023-05-05 16:45:01,566][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 16:45:08,250][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 16:45:08,370][__main__][INFO] - Logging hyperparameters!
[2023-05-05 16:45:40,943][__main__][INFO] - Starting inference!
[2023-05-05 16:59:12,507][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 16:59:12,524][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 16:59:12,525][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 16:59:12,640][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 16:59:12,649][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 16:59:12,654][__main__][INFO] - Instantiating loggers...
[2023-05-05 16:59:12,655][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 16:59:19,511][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 16:59:19,639][__main__][INFO] - Logging hyperparameters!
[2023-05-05 17:00:11,272][__main__][INFO] - Starting inference!
[2023-05-05 17:01:55,301][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_16-59-12
[2023-05-05 17:01:55,302][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 17:13:57,743][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 17:13:57,760][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 17:13:57,760][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 17:13:57,877][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 17:13:57,885][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 17:13:57,890][__main__][INFO] - Instantiating loggers...
[2023-05-05 17:13:57,891][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 17:14:04,217][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 17:14:04,337][__main__][INFO] - Logging hyperparameters!
[2023-05-05 17:14:08,865][__main__][INFO] - Starting inference!
[2023-05-05 17:16:34,862][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_17-13-57
[2023-05-05 17:16:34,863][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:01:41,424][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:01:41,442][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:01:41,443][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:01:41,555][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:01:41,565][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:01:41,570][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:01:41,570][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:01:52,197][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:01:52,320][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:01:58,267][__main__][INFO] - Starting inference!
[2023-05-05 18:02:02,568][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
TypeError: 'method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 100, in infer
    prediction = trainer.predict(model, dataloaders=[datamodule.train_dataloader(shuffle=False), datamodule.test_dataloader])
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <bound method LAFANDataModule.test_dataloader of <src.data.lafan_pose_datamodule.LAFANDataModule object at 0x7f41018c7f70>>.
[2023-05-05 18:02:02,573][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-01-41
[2023-05-05 18:02:02,574][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:03:05,609][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:03:05,625][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:03:05,625][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:03:05,735][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:03:05,744][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:03:05,749][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:03:05,749][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:03:16,416][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:03:16,537][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:03:22,352][__main__][INFO] - Starting inference!
[2023-05-05 18:03:37,426][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
TypeError: 'method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 100, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.test_dataloader))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <bound method LAFANDataModule.test_dataloader of <src.data.lafan_pose_datamodule.LAFANDataModule object at 0x7f44f7f03cd0>>.
[2023-05-05 18:03:37,430][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-03-05
[2023-05-05 18:03:37,431][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:08:47,432][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:08:47,447][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:08:47,448][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:08:47,557][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:08:47,565][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:08:47,571][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:08:47,571][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:08:57,812][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:08:57,934][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:09:26,689][__main__][INFO] - Starting inference!
[2023-05-05 18:10:05,740][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    train_tensors, test_tensors = [extract_tensors_from_prediction(group, i) for group in prediction for i in range(4)]
ValueError: too many values to unpack (expected 2)
[2023-05-05 18:10:05,743][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-08-47
[2023-05-05 18:10:05,744][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:11:39,275][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:11:39,292][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:11:39,293][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:11:39,406][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:11:39,414][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:11:39,420][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:11:39,421][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:11:50,014][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:11:50,148][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:11:52,938][__main__][INFO] - Starting inference!
[2023-05-05 18:12:35,325][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 103, in infer
    train_tensors, test_tensors = [extract_tensors_from_prediction(group, i) for i in range(4) for group in prediction]
ValueError: too many values to unpack (expected 2)
[2023-05-05 18:12:35,328][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-11-39
[2023-05-05 18:12:35,329][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:13:07,744][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:13:07,764][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:13:07,765][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:13:07,894][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:13:07,904][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:13:07,911][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:13:07,912][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:13:18,618][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:13:18,741][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:13:23,932][__main__][INFO] - Starting inference!
[2023-05-05 18:16:50,602][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-13-07
[2023-05-05 18:16:50,603][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:39:19,669][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:39:19,686][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:39:19,686][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:39:19,799][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:39:19,807][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:39:19,812][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:39:19,813][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:39:29,896][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:39:30,018][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:39:31,807][__main__][INFO] - Starting inference!
[2023-05-05 18:39:36,972][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
TypeError: 'method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 101, in infer
    prediction = trainer.predict(model, dataloaders=[datamodule.train_dataloader(shuffle=False), datamodule.test_dataloader])
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <bound method LAFANDataModule.test_dataloader of <src.data.lafan_pose_datamodule.LAFANDataModule object at 0x7f2785a9fd30>>.
[2023-05-05 18:39:36,977][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-39-19
[2023-05-05 18:39:36,977][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:39:55,588][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:39:55,606][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:39:55,607][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:39:55,720][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:39:55,728][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:39:55,733][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:39:55,734][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:40:06,125][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:40:06,243][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:40:07,640][__main__][INFO] - Starting inference!
[2023-05-05 18:43:23,338][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 124, in infer
    shutil.copytree(os.path.join(directory, cat, "anims", name), os.path.join(directory, "all", name), dirs_exist_ok=True)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/shutil.py", line 566, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kinetix/Documents/Hydra/lightning-hydra-template/logs//old_model/train/anims/sigma'
[2023-05-05 18:43:23,343][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-39-55
[2023-05-05 18:43:23,344][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 18:56:26,441][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 18:56:26,457][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 18:56:26,458][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 18:56:26,566][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 18:56:26,576][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 18:56:26,581][__main__][INFO] - Instantiating loggers...
[2023-05-05 18:56:26,581][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 18:56:36,753][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 18:56:36,878][__main__][INFO] - Logging hyperparameters!
[2023-05-05 18:56:39,318][__main__][INFO] - Starting inference!
[2023-05-05 18:56:40,159][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 81, in infer
    datamodule.setup()
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/data/lafan_pose_datamodule.py", line 118, in setup
    self.data_val, self.data_test = check_dataset[:int(len(check_dataset)/2)], check_dataset[int(len(check_dataset)/2):]
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/data/lafan_pose_datamodule.py", line 34, in __getitem__
    return self.data[selectable_index:selectable_index+self.seq_len].reshape(-1)
TypeError: only integer tensors of a single element can be converted to an index
[2023-05-05 18:56:40,162][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_18-56-26
[2023-05-05 18:56:40,163][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 19:00:42,560][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:00:42,576][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:00:42,577][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:00:42,686][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:00:42,696][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:00:42,701][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:00:42,701][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:00:53,100][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:00:53,217][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:01:14,893][__main__][INFO] - Starting inference!
[2023-05-05 19:02:23,144][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:02:23,160][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:02:23,161][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:02:23,267][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:02:23,276][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:02:23,281][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:02:23,282][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:02:33,270][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:02:33,386][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:02:45,356][__main__][INFO] - Starting inference!
[2023-05-05 19:02:51,440][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1352, in _try_put_index
    index = self._next_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 76, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 100, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <torch.utils.data.dataloader.DataLoader object at 0x7fef12d4e340>.
[2023-05-05 19:02:51,446][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_19-02-22
[2023-05-05 19:02:51,446][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 19:03:57,245][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:03:57,261][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:03:57,262][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:03:57,371][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:03:57,380][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:03:57,385][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:03:57,385][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:04:07,411][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:04:07,529][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:04:11,797][__main__][INFO] - Starting inference!
[2023-05-05 19:04:22,579][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1352, in _try_put_index
    index = self._next_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 76, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 100, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <torch.utils.data.dataloader.DataLoader object at 0x7fd8917587f0>.
[2023-05-05 19:04:22,585][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_19-03-57
[2023-05-05 19:04:22,585][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 19:06:20,802][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:06:20,818][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:06:20,819][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:06:20,923][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:06:20,932][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:06:20,936][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:06:20,937][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:06:31,045][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:06:31,165][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:06:33,192][__main__][INFO] - Starting inference!
[2023-05-05 19:06:38,207][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1352, in _try_put_index
    index = self._next_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 76, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 100, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <torch.utils.data.dataloader.DataLoader object at 0x7f3f8b97e790>.
[2023-05-05 19:06:38,212][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_19-06-20
[2023-05-05 19:06:38,213][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 19:08:09,505][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:08:09,522][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:08:09,522][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:08:09,633][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:08:22,820][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:08:22,829][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:08:22,830][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:08:33,088][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:08:33,206][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:08:36,188][__main__][INFO] - Starting inference!
[2023-05-05 19:09:35,616][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1352, in _try_put_index
    index = self._next_index()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 76, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 100, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 101, in run
    self.setup_data()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 144, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 388, in _check_dataloader_iterable
    raise TypeError(
TypeError: An invalid dataloader was passed to `Trainer.predict(dataloaders=...)`. Found <torch.utils.data.dataloader.DataLoader object at 0x7fbbb834f310>.
[2023-05-05 19:09:35,623][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_19-08-09
[2023-05-05 19:09:35,624][src.utils.utils][INFO] - Closing wandb!
[2023-05-05 19:09:45,020][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:09:45,036][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:09:45,037][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:09:45,148][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:09:48,832][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:09:48,840][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:09:48,840][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:09:59,278][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:09:59,391][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:10:02,232][__main__][INFO] - Starting inference!
[2023-05-05 19:12:13,081][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-05 19:12:13,097][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-05 19:12:13,098][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-05 19:12:13,203][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-05 19:12:13,211][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-05 19:12:13,216][__main__][INFO] - Instantiating loggers...
[2023-05-05 19:12:13,217][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-05 19:12:23,398][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-05 19:12:23,513][__main__][INFO] - Logging hyperparameters!
[2023-05-05 19:12:30,445][__main__][INFO] - Starting inference!
[2023-05-05 19:13:31,416][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-05_19-12-12
[2023-05-05 19:13:31,423][src.utils.utils][INFO] - Closing wandb!
[2023-05-09 11:27:11,429][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 11:27:11,454][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 11:27:11,455][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 11:27:11,595][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 11:27:11,605][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 11:27:11,620][__main__][INFO] - Instantiating loggers...
[2023-05-09 11:27:11,620][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-09 11:27:18,248][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 11:27:18,363][__main__][INFO] - Logging hyperparameters!
[2023-05-09 11:27:43,193][__main__][INFO] - Starting inference!
[2023-05-09 11:28:24,973][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_11-27-11
[2023-05-09 11:28:24,974][src.utils.utils][INFO] - Closing wandb!
[2023-05-09 14:14:30,813][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 14:14:30,836][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 14:14:30,837][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 14:14:30,944][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 14:14:30,952][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 14:14:30,957][__main__][INFO] - Instantiating loggers...
[2023-05-09 14:14:30,958][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2023-05-09 14:14:40,723][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 14:14:40,838][__main__][INFO] - Logging hyperparameters!
[2023-05-09 14:15:06,095][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 76, in infer
    model.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 136, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'latent_dim'
[2023-05-09 14:15:08,520][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_14-14-30
[2023-05-09 14:15:08,521][src.utils.utils][INFO] - Closing wandb!
[2023-05-09 14:51:15,018][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 14:51:15,041][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 14:51:15,042][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 14:51:15,042][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 14:51:15,150][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 14:51:15,159][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 14:51:15,164][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 14:51:24,038][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    LightningModule.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 149, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LightningModule:
	Unexpected key(s) in state_dict: "encoder.0.weight", "encoder.0.bias", "encoder.2.weight", "encoder.2.bias", "encoder.4.weight", "encoder.4.bias", "mu.weight", "mu.bias", "log_var.weight", "log_var.bias", "decoder.0.weight", "decoder.0.bias", "decoder.2.weight", "decoder.2.bias", "decoder.4.weight", "decoder.4.bias". 
[2023-05-09 14:51:25,106][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_14-51-14
[2023-05-09 14:52:15,430][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 14:52:15,447][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 14:52:15,447][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 14:52:15,448][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 14:52:15,544][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 14:52:15,552][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 14:52:15,558][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 14:52:18,764][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model._load_from_state_dict(cfg.ckpt_path)
TypeError: _load_from_state_dict() missing 6 required positional arguments: 'prefix', 'local_metadata', 'strict', 'missing_keys', 'unexpected_keys', and 'error_msgs'
[2023-05-09 14:52:18,769][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_14-52-15
[2023-05-09 14:52:55,926][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 14:52:55,943][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 14:52:55,944][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 14:52:55,944][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 14:52:56,046][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 14:52:56,056][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 14:52:56,061][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 14:53:56,109][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 136, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'latent_dim'
[2023-05-09 14:53:56,113][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_14-52-55
[2023-05-09 15:29:48,650][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:29:48,668][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:29:48,669][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:29:48,669][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:29:48,770][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:29:48,778][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 15:29:48,783][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:29:48,911][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = LightningModule.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 149, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LightningModule:
	Unexpected key(s) in state_dict: "encoder.0.weight", "encoder.0.bias", "encoder.2.weight", "encoder.2.bias", "encoder.4.weight", "encoder.4.bias", "mu.weight", "mu.bias", "log_var.weight", "log_var.bias", "decoder.0.weight", "decoder.0.bias", "decoder.2.weight", "decoder.2.bias", "decoder.4.weight", "decoder.4.bias". 
[2023-05-09 15:29:48,915][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-29-48
[2023-05-09 15:30:22,756][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:30:22,773][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:30:22,773][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:30:22,774][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:30:22,868][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:30:22,877][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 15:30:22,882][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:30:23,000][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model._load_from_state_dict(cfg.ckpt_path)
TypeError: _load_from_state_dict() missing 6 required positional arguments: 'prefix', 'local_metadata', 'strict', 'missing_keys', 'unexpected_keys', and 'error_msgs'
[2023-05-09 15:30:23,003][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-30-22
[2023-05-09 15:30:45,855][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:30:45,871][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:30:45,872][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:30:45,872][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:30:45,964][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:30:45,973][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 15:30:45,978][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:30:46,094][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model._load_from_state_dict(cfg.ckpt_path)
TypeError: _load_from_state_dict() missing 6 required positional arguments: 'prefix', 'local_metadata', 'strict', 'missing_keys', 'unexpected_keys', and 'error_msgs'
[2023-05-09 15:30:46,096][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-30-45
[2023-05-09 15:32:17,506][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:32:17,523][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:32:17,523][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:32:17,524][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:32:17,618][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:32:17,626][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 15:32:17,631][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:32:17,746][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = LightningModule._load_from_state_dict(cfg.ckpt_path)
TypeError: _load_from_state_dict() missing 7 required positional arguments: 'state_dict', 'prefix', 'local_metadata', 'strict', 'missing_keys', 'unexpected_keys', and 'error_msgs'
[2023-05-09 15:32:17,749][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-32-17
[2023-05-09 15:33:29,809][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:33:29,825][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:33:29,825][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:33:29,826][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:33:29,916][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:33:29,924][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 15:33:29,929][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:33:30,058][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = LightningModule.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 149, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LightningModule:
	Unexpected key(s) in state_dict: "encoder.0.weight", "encoder.0.bias", "encoder.2.weight", "encoder.2.bias", "encoder.4.weight", "encoder.4.bias", "mu.weight", "mu.bias", "log_var.weight", "log_var.bias", "decoder.0.weight", "decoder.0.bias", "decoder.2.weight", "decoder.2.bias", "decoder.4.weight", "decoder.4.bias". 
[2023-05-09 15:33:30,062][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-33-29
[2023-05-09 15:33:33,931][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:33:33,948][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:33:33,949][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:33:33,949][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:33:34,045][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:33:34,053][__main__][INFO] - Instantiating model <src.models.old_vae.VAE>
[2023-05-09 15:33:34,059][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:33:34,188][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = LightningModule.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 149, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LightningModule:
	Unexpected key(s) in state_dict: "encoder.0.weight", "encoder.0.bias", "encoder.2.weight", "encoder.2.bias", "encoder.4.weight", "encoder.4.bias", "mu.weight", "mu.bias", "log_var.weight", "log_var.bias", "decoder.0.weight", "decoder.0.bias", "decoder.2.weight", "decoder.2.bias", "decoder.4.weight", "decoder.4.bias". 
[2023-05-09 15:33:34,191][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-33-33
[2023-05-09 15:34:56,399][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:34:56,416][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:34:56,416][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:34:56,417][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:34:56,538][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:34:56,549][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:34:56,563][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:34:56,697][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = LightningModule.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 149, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LightningModule:
	Unexpected key(s) in state_dict: "encoder.0.weight", "encoder.0.bias", "encoder.2.weight", "encoder.2.bias", "encoder.4.weight", "encoder.4.bias", "mu.weight", "mu.bias", "log_var.weight", "log_var.bias", "decoder.0.weight", "decoder.0.bias", "decoder.2.weight", "decoder.2.bias", "decoder.4.weight", "decoder.4.bias". 
[2023-05-09 15:34:56,700][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-34-56
[2023-05-09 15:35:13,102][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:35:13,122][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:35:13,122][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:35:13,123][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:35:13,251][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:35:13,260][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:35:13,274][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:35:13,404][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = model.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 136, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 4 required positional arguments: 'optimizer', 'scheduler', 'input_dim', and 'latent_dim'
[2023-05-09 15:35:13,407][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-35-12
[2023-05-09 15:36:06,688][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:36:06,704][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:36:06,705][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:36:06,705][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:36:06,816][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:36:06,824][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:36:06,837][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:36:06,992][__main__][INFO] - Starting inference!
[2023-05-09 15:36:22,072][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:36:22,088][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:36:22,089][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:36:22,089][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:36:22,201][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:36:22,210][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:36:22,223][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:37:28,359][__main__][INFO] - Starting inference!
[2023-05-09 15:37:45,921][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:37:45,937][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:37:45,938][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:37:45,939][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:37:46,053][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:37:46,061][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:37:46,075][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:37:50,220][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = LightningModule.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 136, in _load_state
    obj = cls(**_cls_kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 116, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'optimizer'
[2023-05-09 15:37:51,949][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-37-45
[2023-05-09 15:39:20,266][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:39:20,282][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:39:20,283][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:39:20,283][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:39:20,391][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:39:20,400][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:39:20,413][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:39:32,618][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-09 15:39:32,638][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-09 15:39:32,638][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-09 15:39:32,639][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-09 15:39:32,745][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-09 15:39:32,753][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-09 15:39:32,765][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-09 15:40:00,633][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 68, in infer
    model = model.load_from_checkpoint(cfg.ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 136, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 4 required positional arguments: 'optimizer', 'scheduler', 'input_dim', and 'latent_dim'
[2023-05-09 15:40:03,483][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-09_15-39-32
[2023-05-10 11:30:01,131][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 11:30:01,142][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 11:30:01,142][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 11:30:01,142][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 11:30:01,165][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 11:30:01,168][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 11:30:01,177][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 11:30:02,366][__main__][INFO] - Starting inference!
[2023-05-10 11:30:17,567][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-10_11-30-01
[2023-05-10 11:55:58,326][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 11:55:58,330][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 11:55:58,330][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 11:55:58,330][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 11:55:58,353][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 11:55:58,355][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 11:55:58,365][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 11:55:58,413][__main__][INFO] - Starting inference!
[2023-05-10 11:56:13,862][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-10_11-55-58
[2023-05-10 13:20:02,715][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 13:20:02,719][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 13:20:02,719][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 13:20:02,719][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 13:20:02,743][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 13:20:02,745][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 13:20:02,762][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 13:20:02,805][__main__][INFO] - Starting inference!
[2023-05-10 13:20:18,895][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-10_13-20-02
[2023-05-10 13:23:40,991][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 13:23:40,995][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 13:23:40,995][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 13:23:40,995][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 13:23:41,018][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 13:23:41,020][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 13:23:41,038][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 13:23:41,081][__main__][INFO] - Starting inference!
[2023-05-10 13:23:56,488][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-10_13-23-40
[2023-05-10 14:07:24,027][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 14:07:24,031][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 14:07:24,031][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 14:07:24,031][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 14:07:24,054][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 14:07:24,056][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 14:07:24,068][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 14:07:24,113][__main__][INFO] - Starting inference!
[2023-05-10 14:10:20,056][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 14:10:20,060][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 14:10:20,060][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 14:10:20,060][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 14:10:20,083][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 14:10:20,085][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 14:10:20,105][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 14:10:20,153][__main__][INFO] - Starting inference!
[2023-05-10 14:15:35,016][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 14:15:35,020][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 14:15:35,020][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 14:15:35,020][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 14:15:35,043][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 14:15:35,046][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 14:15:35,065][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 14:15:35,112][__main__][INFO] - Starting inference!
[2023-05-10 14:16:24,254][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 14:16:24,258][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 14:16:24,258][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 14:16:24,258][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 14:16:24,280][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 14:16:24,283][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 14:16:24,301][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 14:16:24,349][__main__][INFO] - Starting inference!
[2023-05-10 14:16:26,248][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 88, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 112, in run
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 228, in _predict_step
    predictions = call._call_strategy_hook(trainer, "predict_step", *step_kwargs.values())
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 396, in predict_step
    return self.model.predict_step(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 887, in predict_step
    return self(batch)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module_debug.py", line 78, in forward
    mu, log_var = self.encode(x)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module_debug.py", line 65, in encode
    mu = self.mu(self.encoder(x))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x720 and 144x256)
[2023-05-10 14:16:26,253][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-10_14-16-24
[2023-05-10 14:17:07,741][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 14:17:07,745][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 14:17:07,745][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 14:17:07,745][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 14:17:07,768][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 14:17:07,770][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 14:17:07,780][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 14:17:07,824][__main__][INFO] - Starting inference!
[2023-05-10 14:17:24,581][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-10_14-17-07
[2023-05-10 14:18:08,409][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-05-10 14:18:08,413][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-05-10 14:18:08,413][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-05-10 14:18:08,414][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-05-10 14:18:08,437][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-10 14:18:08,439][__main__][INFO] - Instantiating model <src.models.beta_vae_module_debug.beta_VAEModule>
[2023-05-10 14:18:08,453][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-10 14:18:08,498][__main__][INFO] - Starting inference!
[2023-05-11 15:10:20,031][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-11 15:10:20,040][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-11 15:10:20,042][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-11 15:10:20,051][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-11 15:10:20,096][__main__][INFO] - Starting inference!
[2023-05-11 15:10:36,212][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-11_15-10-19
[2023-05-12 12:49:46,335][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-12 12:49:46,337][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-12 12:49:46,339][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-12 12:49:46,358][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-12 12:49:46,406][__main__][INFO] - Starting inference!
[2023-05-12 13:00:21,788][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-12 13:00:21,789][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-12 13:00:21,791][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-12 13:00:21,801][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-12 13:00:21,847][__main__][INFO] - Starting inference!
[2023-05-12 13:00:38,801][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-12_13-00-21
[2023-05-15 11:45:17,932][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 11:45:17,940][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-15 11:45:17,943][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 11:45:17,954][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 11:45:17,998][__main__][INFO] - Starting inference!
[2023-05-15 11:45:19,392][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 88, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 112, in run
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 228, in _predict_step
    predictions = call._call_strategy_hook(trainer, "predict_step", *step_kwargs.values())
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 396, in predict_step
    return self.model.predict_step(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 887, in predict_step
    return self(batch)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module.py", line 80, in forward
    mu, log_var = self.encode(x)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module.py", line 67, in encode
    mu = self.mu(self.encoder(x))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x144 and 720x256)
[2023-05-15 11:45:19,395][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-15_11-45-17
[2023-05-15 11:50:54,115][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 11:50:54,117][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-15 11:50:54,119][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 11:50:54,131][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 11:50:54,176][__main__][INFO] - Starting inference!
[2023-05-15 11:51:21,082][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-15_11-50-54
[2023-05-15 15:35:45,835][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 15:35:45,837][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-15 15:35:45,839][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 15:35:45,849][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 15:35:45,902][__main__][INFO] - Starting inference!
[2023-05-15 15:36:02,208][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-15_15-35-45
[2023-05-15 18:24:02,576][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 18:24:02,578][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-05-15 18:24:02,582][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 18:24:02,592][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 18:24:02,636][__main__][INFO] - Starting inference!
[2023-05-15 18:24:19,226][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-15_18-24-02
[2023-05-15 20:44:34,533][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 20:44:34,535][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-15 20:44:34,568][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 20:44:34,584][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 20:44:34,631][__main__][INFO] - Starting inference!
[2023-05-15 20:44:38,297][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 88, in infer
    prediction = trainer.predict(model, dataloaders=(datamodule.train_dataloader(shuffle=False), datamodule.check_dataloader()))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 805, in predict
    return call._call_and_handle_interrupt(
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 847, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run_stage
    return self.predict_loop.run()
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 112, in run
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/loops/prediction_loop.py", line 228, in _predict_step
    predictions = call._call_strategy_hook(trainer, "predict_step", *step_kwargs.values())
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 396, in predict_step
    return self.model.predict_step(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 887, in predict_step
    return self(batch)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module.py", line 80, in forward
    mu, log_var = self.encode(x)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/models/beta_vae_module.py", line 67, in encode
    mu = self.mu(self.encoder(x))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x432 and 144x256)
[2023-05-15 20:44:38,302][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-15_20-44-34
[2023-05-15 20:55:07,419][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 20:55:07,420][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-15 20:55:07,433][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 20:55:07,447][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 20:55:07,493][__main__][INFO] - Starting inference!
[2023-05-15 21:01:01,842][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-15 21:01:01,844][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-15 21:01:01,872][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-15 21:01:01,889][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-15 21:01:01,938][__main__][INFO] - Starting inference!
[2023-05-15 21:01:33,910][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-15_21-01-01
[2023-05-16 14:33:47,812][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-16 14:33:47,815][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-16 14:33:47,827][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-16 14:33:47,837][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-16 14:33:47,882][__main__][INFO] - Starting inference!
[2023-05-16 14:34:04,844][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 115, in infer
    save_tensors(tensor, subdir, directory, prefix, dm)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 83, in save_tensors
    anim_tensor = datamodule.train_dataloader().dataset.model_output_to_pose(y=tensor)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/data/lafan_pose_rot6d_datamodule.py", line 43, in model_output_to_pose
    axisa = kin.matrix_to_rotation_6d(kin.matrix_to_axis_angle(y[:, :6*24].reshape(n_frames, 24, 3, 3))).reshape(n_frames, 24, 3)
RuntimeError: shape '[569317, 24, 3, 3]' is invalid for input of size 81981648
[2023-05-16 14:34:04,846][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-16_14-33-47
[2023-05-16 14:51:25,962][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-16 14:51:25,964][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-16 14:51:25,978][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-16 14:51:25,989][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-16 14:51:26,040][__main__][INFO] - Starting inference!
[2023-05-16 14:51:44,509][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 115, in infer
    save_tensors(tensor, subdir, directory, prefix, dm)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 83, in save_tensors
    anim_tensor = datamodule.train_dataloader().dataset.model_output_to_pose(y=tensor)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/data/lafan_pose_rot6d_datamodule.py", line 43, in model_output_to_pose
    axisa = kin.matrix_to_axis_angle(kin.rotation_6d_to_matrix(y[:, :6*24]))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/kinetix_scenegraph/utils/rotation_conversions.py", line 539, in rotation_6d_to_matrix
    b2 = a2 - (b1 * a2).sum(-1, keepdim=True) * b1
RuntimeError: The size of tensor a (3) must match the size of tensor b (141) at non-singleton dimension 1
[2023-05-16 14:51:44,510][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-16_14-51-25
[2023-05-16 14:52:10,112][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-16 14:52:10,114][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-16 14:52:10,129][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-16 14:52:10,140][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-16 14:52:10,186][__main__][INFO] - Starting inference!
[2023-05-16 14:52:28,044][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 115, in infer
    save_tensors(tensor, subdir, directory, prefix, dm)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/infer.py", line 83, in save_tensors
    anim_tensor = datamodule.train_dataloader().dataset.model_output_to_pose(y=tensor)
  File "/home/kinetix/Documents/Hydra/lightning-hydra-template/src/data/lafan_pose_rot6d_datamodule.py", line 43, in model_output_to_pose
    axisa = kin.matrix_to_axis_angle(kin.rotation_6d_to_matrix(y[:, :6*24]))
  File "/home/kinetix/anaconda3/envs/hydra_env/lib/python3.9/site-packages/kinetix_scenegraph/utils/rotation_conversions.py", line 539, in rotation_6d_to_matrix
    b2 = a2 - (b1 * a2).sum(-1, keepdim=True) * b1
RuntimeError: The size of tensor a (3) must match the size of tensor b (141) at non-singleton dimension 1
[2023-05-16 14:52:28,046][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-16_14-52-10
[2023-05-16 14:54:02,040][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-16 14:54:02,042][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-16 14:54:02,055][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-05-16 14:54:02,067][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-16 14:54:02,113][__main__][INFO] - Starting inference!
[2023-05-16 14:54:34,486][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-16_14-54-01
[2023-05-16 17:20:05,478][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-16 17:20:05,480][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-16 17:20:05,491][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-16 17:20:05,502][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-16 17:20:05,546][__main__][INFO] - Starting inference!
[2023-05-16 17:20:38,160][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-16_17-20-05
[2023-05-17 11:13:41,107][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 11:13:41,109][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 11:13:41,139][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 11:13:41,153][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 11:13:41,200][__main__][INFO] - Starting inference!
[2023-05-17 11:16:24,983][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 11:16:24,985][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 11:16:25,015][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 11:16:25,032][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 11:16:25,081][__main__][INFO] - Starting inference!
[2023-05-17 11:22:33,859][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 11:22:33,864][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 11:22:33,903][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 11:22:33,933][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 11:22:34,053][__main__][INFO] - Starting inference!
[2023-05-17 11:24:07,845][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 11:24:07,850][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 11:24:07,889][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 11:24:07,918][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 11:24:08,034][__main__][INFO] - Starting inference!
[2023-05-17 11:36:33,510][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 11:36:33,512][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 11:36:33,540][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 11:36:33,558][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 11:36:33,608][__main__][INFO] - Starting inference!
[2023-05-17 11:40:56,616][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 11:40:56,618][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 11:40:56,647][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 11:40:56,664][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 11:40:56,712][__main__][INFO] - Starting inference!
[2023-05-17 11:41:27,637][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-17_11-40-56
[2023-05-17 14:56:51,960][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 14:56:51,962][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 14:56:51,975][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 14:56:51,987][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 14:56:52,033][__main__][INFO] - Starting inference!
[2023-05-17 14:58:24,139][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 14:58:24,140][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 14:58:24,170][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 14:58:24,188][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 14:58:24,235][__main__][INFO] - Starting inference!
[2023-05-17 14:58:56,022][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-17_14-58-24
[2023-05-17 15:00:17,185][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-05-17 15:00:17,187][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_rot6d_datamodule.LAFANDataModule>
[2023-05-17 15:00:17,199][__main__][INFO] - Instantiating model <src.models.beta_vae_module_rot6d_loss.beta_VAEModule>
[2023-05-17 15:00:17,217][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-05-17 15:00:17,262][__main__][INFO] - Starting inference!
[2023-05-17 15:00:47,276][src.utils.utils][INFO] - Output dir: /home/kinetix/Documents/Hydra/lightning-hydra-template/logs/infer/runs/2023-05-17_15-00-17
[2023-09-04 01:06:48,069][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-09-04 01:06:48,083][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-09-04 01:06:48,096][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-09-04 01:06:49,067][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-09-04 01:06:49,499][__main__][INFO] - Starting inference!
[2023-09-04 01:07:32,154][src.utils.utils][INFO] - Output dir: /media/omar/9CE41B66E41B4246/Kinetix_backup/stagiaire-omar-mvae/Hydra/lightning-hydra-template/logs/infer/runs/2023-09-04_01-06-47
[2023-09-04 01:25:48,698][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-09-04 01:25:48,711][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-09-04 01:25:48,721][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-09-04 01:25:49,734][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-09-04 01:25:50,184][__main__][INFO] - Starting inference!
[2023-09-04 01:26:34,310][src.utils.utils][INFO] - Output dir: /media/omar/9CE41B66E41B4246/Kinetix_backup/stagiaire-omar-mvae/Hydra/lightning-hydra-template/logs/infer/runs/2023-09-04_01-25-48
[2023-09-04 01:29:55,322][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-09-04 01:29:55,328][__main__][INFO] - Instantiating datamodule <src.data.lafan_pose_datamodule.LAFANDataModule>
[2023-09-04 01:29:55,345][__main__][INFO] - Instantiating model <src.models.beta_vae_module.beta_VAEModule>
[2023-09-04 01:29:56,356][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-09-04 01:29:56,810][__main__][INFO] - Starting inference!
[2023-09-04 01:30:44,210][src.utils.utils][INFO] - Output dir: /media/omar/9CE41B66E41B4246/Kinetix_backup/stagiaire-omar-mvae/Hydra/lightning-hydra-template/logs/infer/runs/2023-09-04_01-29-55
